branch-defaults:
  default:
    environment: django-env-good
    group_suffix: null
environment-defaults:
  django-env-2:
    branch: null
    repository: null
  django-env-3:
    branch: null
    repository: null
global:
  application_name: django-tutorial-good
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
