# Generated by Django 4.0 on 2022-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='page_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
