# Generated by Django 4.0 on 2022-01-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_page_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
