# Generated by Django 4.0 on 2022-01-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_language_description_alter_book_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(help_text='Enter the person who said it.', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
