# Generated by Django 4.0 on 2022-02-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0002_alter_agr_prod_pop_citations_alter_agr_prod_pop_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agr_prod_pop',
            name='citations',
            field=models.ManyToManyField(blank=True, help_text='Select one or more references for this fact. Hold CTRL to select multiple.', related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.Citation'),
        ),
        migrations.AlterField(
            model_name='agr_prod_pop',
            name='name',
            field=models.CharField(default='Agricultural Production and Population', max_length=100),
        ),
        migrations.AlterField(
            model_name='agr_prod_pop',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.polity'),
        ),
        migrations.AlterField(
            model_name='agr_prod_pop',
            name='section',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.section'),
        ),
        migrations.AlterField(
            model_name='agr_prod_pop',
            name='subsection',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.subsection'),
        ),
        migrations.AlterField(
            model_name='majid',
            name='citations',
            field=models.ManyToManyField(blank=True, help_text='Select one or more references for this fact. Hold CTRL to select multiple.', related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.Citation'),
        ),
        migrations.AlterField(
            model_name='majid',
            name='polity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.polity'),
        ),
        migrations.AlterField(
            model_name='majid',
            name='section',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.section'),
        ),
        migrations.AlterField(
            model_name='majid',
            name='subsection',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.subsection'),
        ),
    ]
