# Generated by Django 4.0 on 2022-02-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0003_alter_agr_prod_pop_citations_alter_agr_prod_pop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agr_prod_pop',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.section'),
        ),
        migrations.AlterField(
            model_name='agr_prod_pop',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.subsection'),
        ),
        migrations.AlterField(
            model_name='majid',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.section'),
        ),
        migrations.AlterField(
            model_name='majid',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.subsection'),
        ),
    ]
